version: "3"

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "81:81" 
  dropwizard:
    image: tsprasath91/hello-dropwizard:latest
    restart: always
    expose:
      - "8080:8080"
      - "8081:8081"
